version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    labels:
      - dependencies

